" noplugin if filesize is too big (> 10mb)
let g:largeFileSize = 1024 * 1024 * 10
let g:largeFile = getfsize(expand("%:p")) > g:largeFileSize

" source editor mode and plugin groups
if filereadable(expand("~/.vim/config/config_manual.vim"))
  source ~/.vim/config/config_manual.vim
endif

" load plugins
if filereadable(expand("~/.vim/config/plug.vim"))
  source ~/.vim/config/plug.vim
else
  filetype plugin indent on
endif

" load general vim settings
if filereadable(expand("~/.vim/config/general.vim"))
  source ~/.vim/config/general.vim
endif

" load autocmds
if filereadable(expand("~/.vim/config/autocmd.vim"))
  source ~/.vim/config/autocmd.vim
endif

" load general (non-plugin) keybindings
if filereadable(expand("~/.vim/config/keybindings.vim"))
  source ~/.vim/config/keybindings.vim
endif
